/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Admin
         * @description Dapatkan Token JWT untuk mengakses fitur Admin.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example admin@luma.com */
                        email: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login Berhasil (Simpan token ini) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example eyJhGci... */
                            token?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Logout Admin */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout berhasil */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ambil Semua Produk (Public) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List Produk */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"][];
                    };
                };
            };
        };
        put?: never;
        /** Tambah Produk Baru (Admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        name: string;
                        price: number;
                        description: string;
                        /** @description Upload hingga 20 gambar */
                        images?: string[];
                        /**
                         * @description URL link Trakteer untuk produk ini (opsional)
                         * @example https://trakteer.id/inkvoid/shop/product-name-AbCdE
                         */
                        trakteer_link?: string | null;
                        /**
                         * @description URL file Google Drive (legacy)
                         * @example https://drive.google.com/...
                         */
                        file_url?: string | null;
                        /**
                         * @description JSON stringified array of labels untuk images
                         * @example ["cover", "preview"]
                         */
                        image_labels?: string;
                    };
                };
            };
            responses: {
                /** @description Produk Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized (Token Kosong/Salah) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden (Token Invalid) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/admin/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil Semua Produk (Admin Dashboard)
         * @description Menampilkan produk aktif DAN non-aktif (draft).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List Semua Produk */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle Status Produk (Active/Inactive) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status Berhasil Diubah */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Produk */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        name?: string;
                        price?: number;
                        description?: string;
                        images?: string[];
                        /**
                         * @description URL link Trakteer untuk produk ini (opsional)
                         * @example https://trakteer.id/inkvoid/shop/product-name-AbCdE
                         */
                        trakteer_link?: string | null;
                        /**
                         * @description JSON stringified array of image metadata (url, label, type, order)
                         * @example [{"type":"existing","url":"...","label":"cover","order":0}]
                         */
                        images_metadata?: string;
                    };
                };
            };
            responses: {
                /** @description Update Berhasil */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Hapus Produk Satuan */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Terhapus */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hapus Banyak Produk Sekaligus */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @example [
                         *       1,
                         *       5,
                         *       8
                         *     ]
                         */
                        ids?: number[];
                    };
                };
            };
            responses: {
                /** @description Produk berhasil dihapus */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Buat Transaksi (Snap Token) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        product_id: number;
                        customer_name: string;
                        customer_email: string;
                    };
                };
            };
            responses: {
                /** @description Token Transaksi Dibuat */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook Midtrans (Jangan ditembak manual) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/admin/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lihat Semua Riwayat Transaksi (Admin)
         * @description Mengambil semua riwayat transaksi
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List Transaksi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/admin/transaction/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Status Transaksi (Admin)
         * @description Mengubah status transaksi secara manual (misal: pending -> success).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID Order transaksi */
                    order_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @example success
                         * @enum {string}
                         */
                        status: "pending" | "success" | "failed";
                    };
                };
            };
            responses: {
                /** @description Status berhasil diubah */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Order ID tidak ditemukan */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Pengunjung dengan Pagination (Admin)
         * @description Mengambil daftar semua kunjungan dengan info device, OS, browser. Mendukung pagination via query params.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Nomor halaman (default: 1) */
                    page?: number;
                    /** @description Jumlah data per halaman (default: 10) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Daftar pengunjung berhasil diambil */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /**
                                 * Format: uuid
                                 * @description UUID unik per device/browser
                                 * @example 550e8400-e29b-41d4-a716-446655440000
                                 */
                                visitor_id?: string;
                                /** @example 182.1.100.50 */
                                ip_address?: string;
                                /** @example Mozilla/5.0 (Linux; Android 13)... */
                                user_agent?: string;
                                /** @example Android */
                                os?: string;
                                /** @example Mobile */
                                device_type?: string;
                                /** @example Chrome */
                                browser?: string;
                                /**
                                 * Format: date-time
                                 * @example 2026-03-27T10:30:00Z
                                 */
                                visit_time?: string;
                                /**
                                 * @description Jumlah total kunjungan visitor ini
                                 * @example 5
                                 */
                                visit_count?: number;
                            }[];
                            pagination?: {
                                /** @example 1 */
                                current_page?: number;
                                /** @example 5 */
                                total_pages?: number;
                                /** @example 50 */
                                total_data?: number;
                                /** @example 10 */
                                per_page?: number;
                            };
                        };
                    };
                };
                /** @description Unauthorized (Token kosong) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Akses ditolak. Token tidak ada. */
                            message?: string;
                        };
                    };
                };
                /** @description Forbidden (Token tidak valid) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Token tidak valid. */
                            message?: string;
                        };
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Server Error */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hapus Visitor Satuan (Admin)
         * @description Menghapus satu data visitor berdasarkan ID.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID visitor yang akan dihapus */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Visitor berhasil dihapus */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Visitor berhasil dihapus. */
                            message?: string;
                        };
                    };
                };
                /** @description Unauthorized (Token kosong) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Akses ditolak. Token tidak ada. */
                            message?: string;
                        };
                    };
                };
                /** @description Forbidden (Token tidak valid) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Token tidak valid. */
                            message?: string;
                        };
                    };
                };
                /** @description Visitor tidak ditemukan */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Data visitor tidak ditemukan. */
                            message?: string;
                        };
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hapus Semua Visitor (Admin)
         * @description Menghapus seluruh data kunjungan dari database. Aksi ini tidak dapat dibatalkan.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Semua data visitor berhasil dihapus */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Semua data visitor berhasil dihapus (184 baris). */
                            message?: string;
                        };
                    };
                };
                /** @description Unauthorized (Token kosong) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Akses ditolak. Token tidak ada. */
                            message?: string;
                        };
                    };
                };
                /** @description Forbidden (Token tidak valid) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Token tidak valid. */
                            message?: string;
                        };
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server Health Check
         * @description Cek apakah server berjalan dengan baik (digunakan oleh UptimeRobot/Vercel).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Server is healthy */
                            message?: string;
                            /** @example 120.5 */
                            uptime?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Catat Kunjungan Baru (Public, UPSERT)
         * @description Mencatat kunjungan pengunjung. Jika visitor_id dikirim dan sudah ada di DB, data akan di-UPDATE (visit_count +1, waktu terbaru). Jika belum ada, akan INSERT baru.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description UUID unik per device/browser, disimpan di localStorage frontend
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        visitor_id?: string;
                    };
                };
            };
            responses: {
                /** @description Kunjungan berhasil dicatat/diupdate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Visit recorded */
                            message?: string;
                        };
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil Statistik Pengunjung (Admin)
         * @description Mengambil total views dan unique visitors untuk ditampilkan di Dashboard Admin.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistik berhasil diambil */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example 150 */
                                total_views?: number;
                                /** @example 120 */
                                unique_visitors?: number;
                            };
                        };
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            /** @example 1 */
            id?: number;
            /** @example Sticker Pack Vol. 1 (Chibi Style) */
            name?: string;
            /** @example 15000 */
            price?: number;
            /** @example Stiker lucu format PNG & PDF resolusi tinggi. */
            description?: string;
            /**
             * @description URL gambar utama (diambil dari images[0])
             * @example http://localhost:5000/uploads/1700000000-file.png
             */
            image_url?: string;
            /**
             * @example [
             *       "filename1.png",
             *       "filename2.png"
             *     ]
             */
            images?: string[];
            /**
             * @description 1 = Active/Published, 0 = Inactive/Draft
             * @example 1
             */
            is_active?: number;
            /**
             * @description URL link ke halaman produk di Trakteer (opsional)
             * @example https://trakteer.id/inkvoid/shop/product-name-AbCdE
             */
            trakteer_link?: string | null;
        };
        Transaction: {
            /** @example LUMA-173859... */
            order_id?: string;
            /** @example 15000 */
            gross_amount?: number;
            /** @example Budi */
            customer_name?: string;
            /** @example settlement */
            transaction_status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
